### PR TITLE
tools: remove DRAM-based workloads

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/rpma/11)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
Those new figures can be used ONLY for comparing different benchmarks and NOT for generating a new full report!

:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/11#-:-Mtbk0cTAoi9LUkzO1-3:bgk2lyn)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/11#-:-MtbhOg32O4sVjtMF-PD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/11)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Comment by ldorau** [comment]
The code is available at:  https://github.com/ldorau/rpma/tree/tools-remove-DRAM-based-workloads
This PR will not be merged.

**Pull request closed without merging**
