### PR TITLE
tools: perf: dev: DRAM templates

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/templates/part_dev_dram.md, line 13 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk5xCDa9Gqk-cj417X0:-Mk5xCDb-SPDakkDXEVl:bb7fdgu) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L13)):*
> ```Markdown
> Benchmarking accessing DRAM in two `PCIe Allocating Write Flows` configurations:
> 
> - `Allocating` (along with eADR enabled) and
> ```

fADR
___
*[tools/perf/templates/part_dev_dram.md, line 14 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk5xDw61SGO1fHoT0iI:-Mk5xDw61SGO1fHoT0iJ:b3kqx) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L14)):*
> ```Markdown
> 
> - `Allocating` (along with eADR enabled) and
> - `Non-Allocating` (without eADR)
> ```

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[tools/perf/templates/part_dev_dram.json, line 11 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk6Av6B-G9wavNkrIsq:-Mk6Av6B-G9wavNkrIsr:b-6ukgph) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.json#L11)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>             "Server - ib_read_bw configuration": [
>                 "--size $blocksize --qp 1 --tx-depth=2",
>                 "--size 4096 --qp $threads --tx-depth=2"
>             ],
>             "Client - ib_read_bw configuration": [
>                 "--iters $iters --size $blocksize --qp 1 --tx-depth=2 \\",
>                 "    --report_gbits $serverip",
>                 "--iters $iters --size 4096 --qp $threads --tx-depth=2 \\",
>                 "    --report_gbits $serverip"
>             ],
> ```
</details>

do we need ib_read_bw at all?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/templates/part_dev_dram.md, line 16 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk6F3p_EZWalyAWSywf:-Mk6F3p_EZWalyAWSywg:b-bzfvbf) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L16)):*
> ```
> DRAM is used instead of PMem for benchmarking purposes as the source and the target of the operation which does not
> ```

For benchmarking purposes DRAM is used (instead of PMem) as the source and the target of the operation and it does not ...

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/templates/part_dev_dram.json, line 11 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk6Av6B-G9wavNkrIsq:-Mk6QXfW49jUxOzne4ga:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.json#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>             "Server - ib_read_bw configuration": [
>                 "--size $blocksize --qp 1 --tx-depth=2",
>                 "--size 4096 --qp $threads --tx-depth=2"
>             ],
>             "Client - ib_read_bw configuration": [
>                 "--iters $iters --size $blocksize --qp 1 --tx-depth=2 \\",
>                 "    --report_gbits $serverip",
>                 "--iters $iters --size 4096 --qp $threads --tx-depth=2 \\",
>                 "    --report_gbits $serverip"
>             ],
> ```
do we need ib_read_bw at all?
</blockquote></details>

Done.
___
*[tools/perf/templates/part_dev_dram.md, line 13 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk5xCDa9Gqk-cj417X0:-Mk6QZw8Cd5n-X5kEH0F:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L13)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

fADR
</blockquote></details>

Done.
___
*[tools/perf/templates/part_dev_dram.md, line 14 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk5xDw61SGO1fHoT0iI:-Mk6Q_N8CTaHBeJCd5ly:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L14)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/templates/part_dev_dram.md, line 16 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk6F3p_EZWalyAWSywf:-Mk6S5yXBh3k6XGB5Xio:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> DRAM is used instead of PMem for benchmarking purposes as the source and the target of the operation which does not
> ```

For benchmarking purposes DRAM is used (instead of PMem) as the source and the target of the operation and it does not ...

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[tools/perf/templates/part_dev_dram.md, line 16 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk6F3p_EZWalyAWSywf:-Mk6SSks0bq2O9wBBn_b:b5n83qj) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

which -> what

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/templates/part_dev_dram.md, line 16 at r1](https://reviewable.io/reviews/ldorau/rpma/3#-Mk6F3p_EZWalyAWSywf:-Mk6TCjXCjOpnVj7upeK:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/a2cc867059ec7b8a69af3d654f41fbf9b4dd3f34/tools/perf/templates/part_dev_dram.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

which -> what
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3#-:-Mk6TK6-2UrFH-8gUiVm:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3#-:-Mk6_ptr2VwHocsSLEKJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3#-:-Mk6bJ67EFYHyWM0ZE9P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
