### PR TITLE
tools: perf: dev: DRAM figures

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/figures/dev_dram.json, line 23 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eHhuB6sr63zSCqE2:-Mk2eHhv7cI76xsXV9ca:b-msxgam) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L23)):*
> ```
>                     "_comment": "'PCIe Allocating Write Flows': Allocating",
>                     "direct_write_to_pmem": true
> ```

false
___
*[tools/perf/figures/dev_dram.json, line 31 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eKuV51I0FFxI8xmh:-Mk2eKuV51I0FFxI8xmi:beyqvty) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L31)):*
> ```
>                     "_comment": "'PCIe Allocating Write Flows': Non-Allocating",
>                     "direct_write_to_pmem": false
> ```

true
___
*[tools/perf/figures/dev_dram.json, line 51 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2ehrZ1NBDMv4nYs18:-Mk2ehrZ1NBDMv4nYs19:b-z9sf4s) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L51)):*
> ```JSON
>             "tool_mode": "apm",
>             "rw": "randread",
>             "fstrings": ["label"]
> ```

Maybr add ` "filetype": "malloc",`  here?
___
*[tools/perf/figures/dev_dram.json, line 58 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eR2eErbr_wFSoXA-:-Mk2eR2eErbr_wFSoXA0:b-dorf0f) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L58)):*
> ```
>  "direct_write_to_pmem": true
> ```

false
___
*[tools/perf/figures/dev_dram.json, line 66 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eTgS9BQ_Sh7tM2yx:-Mk2eTgS9BQ_Sh7tM2yy:b3niokf) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L66)):*
> ```
> "direct_write_to_pmem": false
> ```

true
___
*[tools/perf/figures/dev_dram.json, line 82 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eyVIAEgJVSzzl9Pt:-Mk2eyVIAEgJVSzzl9Pu:bgkp5cy) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L82)):*
> ```
> "filetype": "pmem",
> ```

"filetype": "malloc",
___
*[tools/perf/figures/dev_dram.json, line 90 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f21g4nPQqtFhBOxG:-Mk2f21g4nPQqtFhBOxH:b329wgf) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L90)):*
> ```
> "filetype": "malloc",
> ```

common ?
___
*[tools/perf/figures/dev_dram.json, line 93 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f70DA9a2iDsWkiOP:-Mk2f70DA9a2iDsWkiOQ:b-72voth) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L93)):*
> ```
> "direct_write_to_pmem": true
> ```

false
___
*[tools/perf/figures/dev_dram.json, line 98 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f4ZK8H9RhMJhPBXi:-Mk2f4ZK8H9RhMJhPBXj:bbyowbn) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L98)):*
> ```
>  "filetype": "malloc",
> ```

.
___
*[tools/perf/figures/dev_dram.json, line 101 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f90t2sSh52MuKqnO:-Mk2f90t2sSh52MuKqnP:b-7q0dz1) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L101)):*
> ```
> direct_write_to_pmem": false
> ```

true
___
*[tools/perf/figures/dev_dram.json, line 117 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fBI86TAPfhzj9JxQ:-Mk2fBI86TAPfhzj9JxR:b-gp2oie) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L117)):*
> ```
>   "filetype": "pmem",
> ```

malloc
___
*[tools/perf/figures/dev_dram.json, line 125 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fEGH0JPQuPNZgpVI:-Mk2fEGH0JPQuPNZgpVJ:b-h6lenr) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L125)):*
> ```
> "filetype": "malloc",
> ```

.
___
*[tools/perf/figures/dev_dram.json, line 128 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fFrn1_i8vQpDnfKD:-Mk2fFrn1_i8vQpDnfKE:b-72voth) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L128)):*
> ```
> "direct_write_to_pmem": true
> ```

false
___
*[tools/perf/figures/dev_dram.json, line 133 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fIJs0iqy59z75BU_:-Mk2fIJs0iqy59z75BUa:bsz5zqo) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L133)):*
> ```
>   "filetype": "malloc",
> ```

common
___
*[tools/perf/figures/dev_dram.json, line 136 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fK6O5drtf3-YKnRg:-Mk2fK6O5drtf3-YKnRh:b3niokf) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L136)):*
> ```
> "direct_write_to_pmem": false
> ```

true

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 17 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 55 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2k5Rt-dELQo4kK5m9:-Mk2k5Rt-dELQo4kK5mA:b-c2muml) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L55)):*
> ```
>  "filetype": "malloc",
> ```

move to common?
___
*[tools/perf/figures/dev_dram.json, line 63 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2k9x214Dvv7_aehJg:-Mk2k9x214Dvv7_aehJh:bbyowbn) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L63)):*
> ```
>  "filetype": "malloc",
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 51 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2ehrZ1NBDMv4nYs18:-Mk4Mw2rAOWUwe6nixPv:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L51)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 55 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2k5Rt-dELQo4kK5m9:-Mk4MwsD5lfHUEj1WHSp:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "filetype": "malloc",
> ```

move to common?
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 82 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eyVIAEgJVSzzl9Pt:-Mk4MyUnC4d2z3PzInRa:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "filetype": "pmem",
> ```

"filetype": "malloc",
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 90 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f21g4nPQqtFhBOxG:-Mk4MzAJ0DowieIESBQE:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "filetype": "malloc",
> ```

common ?
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 23 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eHhuB6sr63zSCqE2:-Mk4OcS_2OMQUgPc14Av:b-kcyi00) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L23)):*
Please read the template: https://github.com/ldorau/rpma/pull/3/files#diff-0246e36f5617ffb4753ebd60d5e6312eb72d00abe44551b2cd44c67ced5c5e31R11

Knowing that:

> Both configurations achieve *Direct Write to PMem* capability in two different ways.

I think we can agree that differentiating both runs using the `direct_write_to_pmem` is not the perfect solution. But I didn't want to modify the Python framework to achieve the differentiation.

So, I have used this argument in a slightly different way namely:

- `direct_write_to_pmem == true` <=> `PCIe Allocating Write Flows == Allocating` whereas
- `direct_write_to_pmem == false` <=> `PCIe Allocating Write Flows == Non-Allocating`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: 0 of 1 files reviewed, 17 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 63 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2k9x214Dvv7_aehJg:-Mk4Q6835b1vThv4P0LU:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "filetype": "malloc",
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 98 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f4ZK8H9RhMJhPBXi:-Mk4Q9Hn-UJ6HrqEd-l8:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "filetype": "malloc",
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 117 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fBI86TAPfhzj9JxQ:-Mk4PzLw-cyT0me4SWpf:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L117)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>   "filetype": "pmem",
> ```

malloc
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 125 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fEGH0JPQuPNZgpVI:-Mk4Q0-tBuHTQvoEfaWl:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "filetype": "malloc",
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 133 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fIJs0iqy59z75BU_:-Mk4QCN59h5Hd2exRWBc:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>   "filetype": "malloc",
> ```

common
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1#-:-Mk5wmgR9Nuod0zWvZEm:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 80 at r2](https://reviewable.io/reviews/ldorau/rpma/1#-Mk6CdTN3CsIuJHExmrb:-Mk6CdTO9hviMd6tMr41:b-goeo46) ([raw file](https://github.com/ldorau/rpma/blob/8417fd2e0482f5d59b25c6fa09eb458d43edaaef/tools/perf/figures/dev_dram.json#L80)):*
> ```JSON
>             "filetype": "malloc",
>             "mode": "bw-bs",
>             "tool": "rpma_fio_bench.sh",
> ```

Add "tool_mode": "apm"
___
*[tools/perf/figures/dev_dram.json, line 112 at r2](https://reviewable.io/reviews/ldorau/rpma/1#-Mk6Clrm8tZCkdzv7Tg3:-Mk6Clrm8tZCkdzv7Tg4:b3kqx) ([raw file](https://github.com/ldorau/rpma/blob/8417fd2e0482f5d59b25c6fa09eb458d43edaaef/tools/perf/figures/dev_dram.json#L112)):*
> ```JSON
>             "filetype": "malloc",
>             "mode": "bw-th",
>             "tool": "rpma_fio_bench.sh",
> ```

.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 23 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eHhuB6sr63zSCqE2:-Mk6CBiA2kxPRnmuE3OO:b-iyhz8p) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please read the template: https://github.com/ldorau/rpma/pull/3/files#diff-0246e36f5617ffb4753ebd60d5e6312eb72d00abe44551b2cd44c67ced5c5e31R11

Knowing that:

> Both configurations achieve *Direct Write to PMem* capability in two different ways.

I think we can agree that differentiating both runs using the `direct_write_to_pmem` is not the perfect solution. But I didn't want to modify the Python framework to achieve the differentiation.

So, I have used this argument in a slightly different way namely:

- `direct_write_to_pmem == true` <=> `PCIe Allocating Write Flows == Allocating` whereas
- `direct_write_to_pmem == false` <=> `PCIe Allocating Write Flows == Non-Allocating`
</blockquote></details>

can we use reverse logic (as @ldorau ) suggest?
for historical reasons non-allocating has been assigned to direct_write_to_pmem

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/figures/dev_dram.json, line 23 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eHhuB6sr63zSCqE2:-Mk6IQElEEckDtZsvVu2:b35pgei) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

can we use reverse logic (as @ldorau ) suggest?
for historical reasons non-allocating has been assigned to direct_write_to_pmem

</blockquote></details>

It has been the opposite so far ?!? ...

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/figures/dev_dram.json, line 23 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eHhuB6sr63zSCqE2:-Mk6PAZ28lA8NhPr9jex:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It has been the opposite so far ?!? ...
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 31 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eKuV51I0FFxI8xmh:-Mk6PBmw24tbF-e2wAHg:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>                     "_comment": "'PCIe Allocating Write Flows': Non-Allocating",
>                     "direct_write_to_pmem": false
> ```

true
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 58 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eR2eErbr_wFSoXA-:-Mk6PCfJDXo2ClJJKS9r:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "direct_write_to_pmem": true
> ```

false
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 66 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2eTgS9BQ_Sh7tM2yx:-Mk6PDQI244Cr6WOOnRK:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "direct_write_to_pmem": false
> ```

true
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 93 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f70DA9a2iDsWkiOP:-Mk6PFuw9QL9y0sf6dra:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "direct_write_to_pmem": true
> ```

false
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 101 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2f90t2sSh52MuKqnO:-Mk6PGtf5CalWiMw879W:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> direct_write_to_pmem": false
> ```

true
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 128 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fFrn1_i8vQpDnfKD:-Mk6PHlS86BdvQ-OGH8J:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L128)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "direct_write_to_pmem": true
> ```

false
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 136 at r1](https://reviewable.io/reviews/ldorau/rpma/1#-Mk2fK6O5drtf3-YKnRg:-Mk6PIe8B175VTkg5BRG:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/186e3a2132c67ebd3dcb6e8215d461732ec952e8/tools/perf/figures/dev_dram.json#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "direct_write_to_pmem": false
> ```

true
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/figures/dev_dram.json, line 80 at r2](https://reviewable.io/reviews/ldorau/rpma/1#-Mk6CdTN3CsIuJHExmrb:-Mk6PnSU3pVgiyEFh0xD:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/8417fd2e0482f5d59b25c6fa09eb458d43edaaef/tools/perf/figures/dev_dram.json#L80)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Add "tool_mode": "apm"
</blockquote></details>

Done.
___
*[tools/perf/figures/dev_dram.json, line 112 at r2](https://reviewable.io/reviews/ldorau/rpma/1#-Mk6Clrm8tZCkdzv7Tg3:-Mk6PoKB9otE1DLUWHsJ:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/8417fd2e0482f5d59b25c6fa09eb458d43edaaef/tools/perf/figures/dev_dram.json#L112)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1#-:-Mk6QMteE5JC5luF7qIp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1#-:-Mk6QTfU8e_zei5C-uE4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
