### PR TITLE
tools: remove skipping if RDW2PMEM != RRDW2PMEM

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4#-:-Mk6c0V0EdSFEskLcN5r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/bench_common.sh, line 232 at r1](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6i97-4x0O2rfT1akQ:-Mk6i97-4x0O2rfT1akR:b-oyamsn) ([raw file](https://github.com/ldorau/rpma/blob/81b0eabfbb8a070524cdb3c4565f5ffffeb4349f/tools/perf/bench_common.sh#L232)):*
> ```Shell
> 		echo "Error: REMOTE_DIRECT_WRITE_TO_PMEM does not have the required value ($REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM)"
> 		echo "Skipping..."
> 		exit 0
> ```

I recommend just commenting it out. And adding a comment e.g.:

```sh
# XXX Python does not handle skips correctly and controls the requirements on its own so this check only prevents Python from doing its job.
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/bench_common.sh, line 232 at r1](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6i97-4x0O2rfT1akQ:-Mk6lOPV7KIqwrMfRAT0:b32v57) ([raw file](https://github.com/ldorau/rpma/blob/81b0eabfbb8a070524cdb3c4565f5ffffeb4349f/tools/perf/bench_common.sh#L232)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend just commenting it out. And adding a comment e.g.:

```sh
# XXX Python does not handle skips correctly and controls the requirements on its own so this check only prevents Python from doing its job.
```
</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/bench_common.sh, line 232 at r1](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6i97-4x0O2rfT1akQ:-Mk6oOBS5UUQDRvIKO5m:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/81b0eabfbb8a070524cdb3c4565f5ffffeb4349f/tools/perf/bench_common.sh#L232)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/bench_common.sh, line 229 at r2](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6od8Y6NoOhCaYEAE_:-Mk6od8Y6NoOhCaYEAEa:bny40hk) ([raw file](https://github.com/ldorau/rpma/blob/77ff0b63fe57fe1b5c954b9d670d88b017f59c1b/tools/perf/bench_common.sh#L229)):*
> ```
> 		REMOTE_DIRECT_WRITE_TO_PMEM=$REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM
> 	# XXX Python does not handle skips correctly and controls
> ```

Please add one empy comment line:
```
		REMOTE_DIRECT_WRITE_TO_PMEM=$REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM
	#
	# XXX Python does not handle skips correctly and controls
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/bench_common.sh, line 229 at r2](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6od8Y6NoOhCaYEAE_:-Mk6p9BwCM5xXZCkFy9H:b-896fix) ([raw file](https://github.com/ldorau/rpma/blob/77ff0b63fe57fe1b5c954b9d670d88b017f59c1b/tools/perf/bench_common.sh#L229)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		REMOTE_DIRECT_WRITE_TO_PMEM=$REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM
> 	# XXX Python does not handle skips correctly and controls
> ```

Please add one empy comment line:
```
		REMOTE_DIRECT_WRITE_TO_PMEM=$REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM
	#
	# XXX Python does not handle skips correctly and controls
```
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:goat: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4#-:-Mk6phAp4byIkXspYH9X:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6pcuy2giUtTB2Vw6k:-Mk6pcuzCEmytkK9h-eX:bifr9mp) (no related file):*
@ldorau has you verified it solves the problem?

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6pcuy2giUtTB2Vw6k:-Mk6ppm008bQS73hjYKN:b3e57q8) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ldorau has you verified it solves the problem?
</blockquote></details>

I am still verifying that...

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6pcuy2giUtTB2Vw6k:-Mk6tGxG6F81qftCnWNG:bdziqpr) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I am still verifying that...
</blockquote></details>

It seems it does not :-(

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6pcuy2giUtTB2Vw6k:-Mk7PBJP3SGnfsCzW6xh:b-fg380t) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems it does not :-(
</blockquote></details>

It seems we need also this fix: pmem/rpma#1291

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/ldorau/rpma/4#-Mk6pcuy2giUtTB2Vw6k:-Mk7TjLR7_q1wn5duYxy:b-7mnj3i) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems we need also this fix: pmem/rpma#1291
</blockquote></details>

Verifying ...

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4#-:-Mk7hTIM32nZVaioZwBf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ldorau/rpma/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
